"""Temporary namespaced styling for application-specific legacy bodies.

This is deliberately outside the reusable UI package. It preserves accepted
domain layouts while they consume the standard shell and tokens.
"""

from .ui.render import (
    SafeHtml,
    render_legacy_compatibility,
    render_stylesheet_extension,
)


def compatibility_body(markup: str) -> SafeHtml:
    """Route accepted legacy application markup through the standard renderer."""
    return render_legacy_compatibility(markup)


COMPATIBILITY_CSS = r"""
.compat-application .interface-section{margin:1rem 0;padding:1rem 0;border-top:1px solid var(--ui-border)}
.compat-application .interface-section:first-of-type{border-top:0}.compat-application .interface-section>h2{margin:.1rem 0 .45rem;font-size:1.1rem}.compat-application .interface-section>p{max-width:65ch;color:var(--ui-text-secondary);font-size:.86rem}
.compat-application .interface-field{display:block;margin:1rem 0}.compat-application .interface-field strong{font-size:.82rem;font-weight:600}.compat-application .interface-field input,.compat-application .interface-field textarea,.compat-application .interface-field select{display:block;width:100%;min-height:2.5rem;margin:.35rem 0;padding:.5rem .65rem;border:1px solid var(--ui-border-strong);border-radius:6px;background:var(--ui-surface);font-size:.86rem}.compat-application .interface-field textarea{min-height:5.5rem}.compat-application small{display:block;color:var(--ui-text-muted);font-size:.72rem}
.compat-application .interface-actions{display:flex;flex-wrap:wrap;gap:.45rem;align-items:flex-start}.compat-application .interface-actions form{margin:0}.compat-application .interface-actions input[type=hidden]{display:none}.compat-application .interface-actions .confirm{display:inline-flex;min-height:2.25rem;align-items:center;gap:.35rem;font-size:.78rem}.compat-application .interface-actions>.ui-confirmation{flex-basis:100%;margin-top:.55rem;padding-top:.7rem;border-top:1px solid var(--ui-border)}.compat-application .watch-row{margin:.4rem 0;padding:.85rem;border:1px solid var(--ui-border);border-radius:8px;background:var(--ui-surface)}.compat-application .watch-row h3{margin:0 0 .35rem;font-size:.9rem}.compat-application .watch-row p{margin:.35rem 0;color:var(--ui-text-secondary);font-size:.8rem;font-variant-numeric:tabular-nums}.compat-application .authority-note{flex-basis:100%}.compat-application .about-panel{margin:1.25rem 0;border-top:1px solid var(--ui-border);padding-top:.4rem}.compat-application .about-panel>summary{display:flex;min-height:2.5rem;align-items:center;color:var(--ui-text-secondary);font-size:.8rem;font-weight:600;cursor:pointer}.compat-application pre{overflow:auto;white-space:pre-wrap;word-break:break-word;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.78rem}
.compat-application .listing-summary{display:flex;flex-wrap:wrap;gap:.5rem 1.4rem;margin:.75rem 0;color:var(--ui-text-secondary);font-size:.8rem}.compat-application .listing-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.compat-application .listing-card{padding:.9rem;border:1px solid var(--ui-border);border-radius:8px;background:var(--ui-surface)}.compat-application .listing-card h3{margin:.3rem 0;font-size:.9rem}.compat-application .listing-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.55rem;margin:.75rem 0;font-size:.82rem}.compat-application .listing-facts span{display:block;color:var(--ui-text-muted);font-size:.7rem}.compat-application .disposition{display:inline-flex;min-height:1.55rem;align-items:center;color:var(--ui-text-secondary);font-size:.72rem;font-weight:600}.compat-application .back-link{display:inline-flex;min-height:2rem;align-items:center;font-size:.8rem}.compat-application .receipt{color:var(--ui-text-muted);font-size:.72rem}.compat-application .muted{color:var(--ui-text-muted)}
.card{margin:.6rem 0;padding:.85rem;border:1px solid var(--ui-border);border-radius:8px;background:var(--ui-surface)}.card h2,.card h3{margin-top:.2rem}.clarification-card{border-left:3px solid var(--ui-warning)}.problem-card{border-left:3px solid var(--ui-danger)}.build-proposal{padding:.65rem;background:var(--ui-surface-subtle)}.notice{margin:.65rem 0;padding:.75rem;border-left:3px solid var(--ui-focus);background:var(--ui-surface-subtle);color:var(--ui-text-secondary);font-size:.84rem}.button,.resource,button,.file-button{display:inline-flex;min-height:2.25rem;align-items:center;justify-content:center;border:1px solid transparent;border-radius:6px;background:var(--ui-action);color:var(--ui-text-inverse);padding:.42rem .72rem;font-size:.82rem;font-weight:600;text-decoration:none;cursor:pointer}.button:hover,button:hover,.file-button:hover{background:var(--ui-action-hover)}.secondary,.resource.secondary{border-color:var(--ui-border);background:var(--ui-surface);color:var(--ui-text)}.secondary:hover,.resource.secondary:hover{background:var(--ui-surface-hover)}button:disabled{cursor:not-allowed;opacity:.48}.technical{margin-top:.75rem;border-top:1px solid var(--ui-border);color:var(--ui-text-muted);font-size:.76rem}.technical summary{display:flex;min-height:2.25rem;align-items:center;cursor:pointer}.technical dl{display:grid;grid-template-columns:auto minmax(0,1fr);gap:.3rem .75rem}.technical dd{margin:0;overflow-wrap:anywhere}.resource{margin:.3rem .3rem 0 0}.login{max-width:28rem;margin:12vh auto;padding:1.5rem;border:1px solid var(--ui-border);border-radius:10px;background:var(--ui-surface)}.login input{width:100%;min-height:2.5rem;margin:.65rem 0;border:1px solid var(--ui-border-strong);border-radius:6px;padding:.5rem}.empty{padding:4rem 1rem;color:var(--ui-text-secondary);text-align:center}
.page-eyebrow{margin:0;color:var(--ui-accent);font-size:.75rem;font-weight:600}.page-title{max-width:28ch;margin:.15rem 0;font-size:1.5rem;line-height:2rem;letter-spacing:-.035em}.page-intro{max-width:65ch;margin:.4rem 0 1.5rem;color:var(--ui-text-secondary);font-size:.9rem}.application-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;border-block:1px solid var(--ui-border)}.application-card{display:flex;min-height:8rem;flex-direction:column;padding:1rem;background:var(--ui-surface)}.application-card+.application-card{border-left:1px solid var(--ui-border)}.application-card h2{margin:0;font-size:.95rem}.application-card p{margin:.3rem 0;color:var(--ui-text-secondary);font-size:.82rem}.application-card .button{align-self:flex-start;margin-top:auto}
@media(max-width:760px){.ui-main{min-width:0}}
@media(max-width:639px){.compat-application .listing-grid{grid-template-columns:1fr}.compat-application .listing-facts{grid-template-columns:repeat(2,minmax(0,1fr))}.compat-application .interface-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.compat-application .interface-actions>form,.compat-application .interface-actions>form button{width:100%}.compat-application .interface-actions>details{grid-column:1/-1}.compat-application .watch-row{padding:.75rem}.application-grid{grid-template-columns:1fr}.application-card+.application-card{border-left:0;border-top:1px solid var(--ui-border)}}
"""


COMPATIBILITY_STYLESHEET = render_stylesheet_extension(COMPATIBILITY_CSS)
